/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ppsbbs.myserver;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        try {
        //启动server服务
        new NettyServer().bind(18081);
            
        } catch (Exception e) {
            //TODO: handle exception
        }
    }
}
