/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ppsbbs.myclient;
import io.netty.channel.Channel;
import java.util.UUID;

public class App {

    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        try {
        NettyClient client = new NettyClient("127.0.0.1", 18081);
        client.start();
        Channel channel = client.getChannel();
        //消息体
        RpcRequest request = new RpcRequest();
        request.setId(UUID.randomUUID().toString());
        request.setData("client.message");
        //channel对象可保存在map中，供其它地方发送消息
        channel.writeAndFlush(request);
        
        } catch (Exception e) {
            //TODO: handle exception
        }
    }
}
